#!/bin/bash

######################################################
# This is the sample output of node

Authore : P.Kumar


Date: 29-03-2024


######################################################

# Above is metadata information


